### ISSUE TITLE
[JOSS Review] Software testing

### ISSUE THREAD

**Issue by oesteban** [raamana/hiwenet#10]
The main missing point here is a "smoke test" (just checking that the software worked, allowing any size of error at the output). How it would work:

1. Generate an example features file. Store it in your repo so travis fetches it.
2. Generate (locally) the outputs from that specific features file. Add it to the repo.
3. Run the command line on that file (use coverage if you want to make sure that run is taken into account for coverage measure, allowing you to get rid of some tests -I go deeper on this below-).
4. Check that the output of 3) is the same you got in 2).

This does not check that the method worked correctly, it only checks that it did not break down (no smoke came out the box).

But, **you happen to have an alternative implementation**. This is a great _testing oracle_. You will be able to 1) ensure your implementation matches the original; 2) be more certain about the correctness of your software. To do so, modify 2) in the previous list with the outputs generated with your Matlab implementation. In 4) you probably want to modify your test to accept certain threshold of numerical tolerance. After all, *you wouldn't need to repeat all the experiments of your preprint to provide some evidence that this implementation is equivalent*.

The rest of the tests just check the conformity of inputs and outputs (https://github.com/raamana/hiwenet/blob/c4fc23b837f072888f5a359ac4df0e1c38ba5d8e/hiwenet/test_hiwenet.py#L46-L110), which is fine.

Or they test argparse, when it already takes care of the correctness and interpretation of the command line. I think these tests do not exercise much the code: https://github.com/raamana/hiwenet/blob/c4fc23b837f072888f5a359ac4df0e1c38ba5d8e/hiwenet/test_hiwenet.py#L113-L168 .

(ref. https://github.com/openjournals/joss-reviews/issues/380)

**Comment by raamana** [comment]
Man, you're incredibly patient to write a detailed issue 👍 

Anyways if I understand you and suggested test correctly, this will be testing the I/O aspects of hiwenet, more so than the implementation itself. Yes? I think this is important if we were to offer both interfaces -- working on it.

**Comment by oesteban** [comment]
I proposed two "flavors":

1. Vanilla:
  - exercises the i/o aspects (as you will see, the coverage will not drop if you remove all the tests on the command line).
  - but more importantly: will let you know when something is broken inside the extract function (meaning, you make a mistake coding and you catch the problem early)

2. Cross-validated:
  - in addition to the vanilla, you will provide proof that the python implementation is close enough to the matlab implementation

**Comment by raamana** [comment]
The 9bcc307dbcd28c96b739eeaa989b3264fd2eef49 should resolve item 1 here (involving API, CLI an I/O).

The second one is more about matching [medpy's](GitHub.com/loli/medpy) implementation with that coming from the [matlab toolbox](http://www.mathworks.com/matlabcentral/fileexchange/39275-histogram-distances). This comparison is complicated and non-trivial, which I feel is slightly beyond the scope of this package/review. It is important for my research and I will dig into it as I try to make comparisons between them.

**Comment by oesteban** [comment]
I believe it would make sense to extend the added test to all metrics, but I leave this decision to @raamana.

I also consider that test 2 is not that hard to implement (it just takes pre-calculating the features file on a certain dataset with the MATLAB version and check that it is close enough to the features calculated from the same dataset with python, and the dataset does not need to come from a real brain, they could just be randomly generated). This test would add real value to the testing effort. As I said, it is not something I consider mandatory, so I'll close this issue.

**Comment by raamana** [comment]
Thanks Oscar, its definitely to run the CLI vs API matching test to all metrics, I haven't done, as I believe if it does for one, it should also behave the same for others, and I didn't want to elongate the tests for no obvious reasons. I will extend them.

Regarding matlab vs python, as I mentioned before, I expect them to differ as they are implemented by different people , possibly with different equations, although being in the same family. Moreover, i don't any consider any to be a reference or ground truth - each are simply a different instantiation (although with different implementations). I agree with you doing this is way better than otherwise, I hope to do it when I am able to, or when I am able to find other resources (like a coop project).

**Comment by raamana** [comment]
CLI vs API matching test has been extended - via fb224f23f03b2e537fb94027f0b2a84ded836d44 -  to all metrics and semi metrics now, thanks for pointing it out.
