### ISSUE TITLE
[JOSS Review] Please indicate clearly that the software is not Python 3 compatible

### ISSUE THREAD

**Issue by oesteban** [raamana/hiwenet#2]
The software only works on Python 2. Given the current size of the project (small) and the fact that Python 2 has been discontinued, I would strongly suggest moving forward and start supporting Python 3 now.

In my opinion, no backwards compatibility is necessary. So it is up to the authors to keep it or dismiss it.

If making this software Python 3 compatible is not in the roadmap, both points should be made very clear in the top README file of the project.

It is true that the authors are using the appropriate classifiers for Pypi, but those classifiers are not taken into account by `pip` during installation. Long story short: installation works in a Python 3 environment without even a warning.

(ref https://github.com/openjournals/joss-reviews/issues/380)

**Comment by raamana** [comment]
You're absolutely right - Python 3 comptibility is definitely in the roadmap, just a matter of time for me to work my way through packaging and getting it to work.

From my initial trials, it was not easy (interactions with different packages were not easy to debug). This was suprising as there is nothing in the code that's complicated and not expected to work across multiple versions (atleast PyCharm thinks that way).

I can perhaps take your tips to make it Python 3 compatible.

**Comment by oesteban** [comment]
I would strongly advise to that. I would also advise to drop Python 2 compatibility, even though it may limit (very little, that must be said), the community of users.

But attaching to Python 2 it does really limit the space of users (as a matter of fact I will need to start a python 2 environment which I don't have in my desktop... :D)

**Comment by raamana** [comment]
updated the readme as suggested.

**Comment by raamana** [comment]
True, I will move to python 3-only environment in few weeks after my deadlines are done.

**Comment by raamana** [comment]
Hey Oscar, check #6 to see my attempts for compatibility. A dependency is holding me back.
