### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by raamana** [raamana/hiwenet#6]
Due to single a statement not compatible with Python 3+ in medpy at
https://github.com/loli/medpy/blob/master/medpy/core/logger.py#L94

The current version on GitHub shows it as fixed, but not the one on PyPI (3 years old)

I'm unable to upgrade hiwenet to python 3+ easily. 

Need to figure out workarounds - perhaps restricting medpy import to very specific things (not ever getting that error).

**Comment by raamana** [comment]
the current implementation does with 2.7
https://travis-ci.org/raamana/hiwenet/jobs/271788219

but not with 3+ due to medpy not being compatible with py3+.

**Comment by oesteban** [comment]
Hi, I have contacted the author of medpy (Oskar). He will try to push for Python 3 compatibility ASAP. I know Oskar and I'm pretty sure he meant it. However, I don't think the Python 3 compatibility is necessary for the JOSS submission. It may happen after acceptance.

**Comment by raamana** [comment]
Thanks Oscar (with a c), and you and Oskar (with k) are both amazing :)

I am going to try contribute to medpy in other areas as well as I go along.
