### ISSUE TITLE
[JOSS Review] API is not documented

### ISSUE THREAD

**Issue by oesteban** [raamana/hiwenet#7]
Methods are documented with docstrings, but no automated method to produce the API documentation is available. Using sphinx would be really straightforward to document this project properly.

This software would really improve if documentation was built automatically and served by a third-party service like http://readthedocs.org

(ref. https://github.com/openjournals/joss-reviews/issues/380)

**Comment by raamana** [comment]
Hey Oscar, check the docs website now: http://hiwenet.readthedocs.io

The API page compiles properly locally, but not on RTD. It did once, it seems it is flaky when using sphinx-argparse extension. Will work with them to fix it.

**Comment by raamana** [comment]
Actually, it just worked again :). Open this if you have suggestions to improve.

Thanks for your comments Oscar, really improving the repo.

**Comment by oesteban** [comment]
Thanks a lot, this is a lot more convenient.

Some minor suggestions:

- Usage section should be renamed to Examples
- The command line interface section should not be under the API section. You could extract it and name it Usage (this time it is appropriate). One example of command line (one line) would be very much appreciated.
- Add a section "original implementation" where you include the original Matlab code and comment on which ways this implementation differs.

**Comment by raamana** [comment]
Done.

I don't think the reference to original implementation is so important.

**Comment by oesteban** [comment]
The fact that there is a primitive/original implementation in Matlab is irrelevant, just a circumstance. However, being transparent about the fact is very important.
