### ISSUE TITLE
[JOSS review] Discussion and Clarifications 

### ISSUE THREAD

**Issue by oesteban** [raamana/hiwenet#8]
From http://joss.theoj.org/about#author_guidelines:

> *What are your requirements for submission?*
>
>  - [x] Your software should be open source as per the OSI definition
>  - [x] Your software should have an obvious research application
>  - [x] You should be a major contributor to the software you are submitting
>  - [x] Should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)
>  - [ ] Should be feature complete (no half-baked solutions)
>  - [ ] Minor, 'utility' packages are not acceptable
> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.

1. The point _Should be feature complete (no half-baked solutions)_ could be ticked on, but some details (as the fact that no automated generation of documentation is provided #7 ) points to the opposite. Tests are probably a bit light as well (will post a different issue with more concrete ideas). These issues can be addressed during the review process.

2. But I'm mostly concerned about the last point: _Minor, 'utility' packages are not acceptable_. The core of the proposed package is [the extract function](https://github.com/raamana/hiwenet/blob/0e2ed2e667c7093d717482ea3dd301fa11421b01/hiwenet/hiwenet.py#L59-L167) which computes the histograms for each ROI in the parcellation and then uses the histogram distance function from medpy to calculate the histogram-weighted network. The code is completed by some eight supporting functions that basically wrap methods from numpy and medpy to address particular operations. I would like to hear from Pradeep the aspects along which this package goes beyond the concept of 'utility'.

    **This is a very valuable piece of code and a great contribution to network analysis**, please do not get me wrong. But I would find it extremely more useful (and accessible to a wider audience) if it was integrated in other neuroimaging packages, like MNE, nilearn, nistats, medpy (which is a dependency) or even nibabel. Was a PR requested to any of these projects and rejected in first place? These packages always credit contributors and reference the original methods, so I don't see the downside.

    Particularly, nilearn currently misses the calculation of histogram-weighted networks and formal utilities for signal extraction from surface (it can be done, but with some manual massaging). Adding these two features (which is, basically what HiWiNet does currently) to nilearn would be extremely useful. And, hiwinets could be calculated on volume-based data as well, at no extra cost.

(ref. https://github.com/openjournals/joss-reviews/issues/380)

**Comment by raamana** [comment]
Your points are well taken, Oscar. Here is a very quick repsonse to your points
 - I agree auto-generation of docs is ideal and will work towards it soon.
 - I am curious to learn how my tests were light
 - I think you've answered your own question/critique :). Quickly, I believe in the Unix philosophy for tool building, and the scope of hiwenet was decided with that in mind. Because, the function hiwenet serves is generic (I mean beyond neuroscience, not just a modalities like fMRI or MEG etc), having it separate from the popular aforementioned packages (meaning not restricting it to nilearn or MNE etc) is a strength IMHO. As you know, developers there can easily plug this in (in additon to other types of covariance estimates, as histogram distances is only one family). I imagine (and am hoping to) add more families of distances, as I find time or help from others. 
 - Counter example to your comments are (following the Unix philosophy), are two of my favourite commands: `wc` and `split`. They each do only one thing and they do them well. That's what I hope hiwenet is and will be.

Pinging @cmadan for comments.

**Comment by raamana** [comment]
Also, have you taken a look around on JOSS list of accepted papers?

**Comment by oesteban** [comment]
> I agree auto-generation of docs is ideal and will work towards it soon.

Nice!

> I am curious to learn how my tests were light

Sure, I'll try to help as much as I can on this :)

> I think you've answered your own question/critique :).

I hope not, my intention is to help. It's not to discuss with myself alone :D

> Quickly, I believe in the Unix philosophy for tool building, and the scope of hiwenet was decided with that in mind. Because, the function hiwenet serves is generic (I mean beyond neuroscience, not just a modalities like fMRI or MEG etc), having it separate from the popular aforementioned packages (meaning not restricting it to nilearn or MNE etc) is a strength IMHO. 

I also do believe in the Unix philosophy, but here the discussion is different: 

  **is hiwenet a 'utility' or not?**.


As regards the generality of hiwenet, let's be precise (please correct me if I wrongly understood the following). There are two main components:
  - The generation of hiwenets, where the inputs are features and the output is a network
  - Some code around that, to enable taking in surfaces and generating the features table on which the histograms are computed.

The first is the core component of the contribution, and could be used (as you mention) importing it from a different package (strengthening the idea of utility).
The second is necessary for making the tool command-line usable and to enable some more standard outputs (which is fine, but as I mention below, you could use nibabel+numpy or MNE to do the same).

MNE is very generic and provides large support to reading surfaces and applying parcellations to extract signals. This could be brains or whatever object. Examples in nilearn are only on volumes and here you have the example of how to calculate the connectivity (without the histogram weighting which is missing in nilearn): http://nilearn.github.io/connectivity/region_extraction.html#computing-functional-connectivity-matrices. This can be applied to fMRI or whatever 3D data.

> As you know, developers there can easily plug this in (in additon to other types of covariance estimates, as histogram distances is only one family). I imagine (and am hoping to) add more families of distances, as I find time or help from others.

Integrating your code in a well-established package will supercharge the visibility of your contribution. It will also make it more "open-sourcy", not less (as you suggest with the Unix philosophy idea).

> Counter example to your comments are (following the Unix philosophy), are two of my favourite commands: wc and split. They each do only one thing and they do them well. That's what I hope hiwenet is and will be.

They are, as you say, two beautiful _utilities_ that require tests, maintenance, and love in general. Again, this is not the question.

As a reviewer, I just raise the question. Now, the interpretation of my question and your answers belongs in @cMadan's responsibilities as you mentioned.

To wrap-up, as a reviewer, I am trying to push in two directions here:
  - Get an explicit answer to the central question I raised (regardless the interpretation of your answers that corresponds to the editors).
  - Get an idea of how well I described this software above (about the two components of hiwenet). I could be missing something.

In the end, your responses to both points will help better define the Statement of need for this software and the scope of its features.

**Comment by oesteban** [comment]
> Also, have you taken a look around on JOSS list of accepted papers?

Can you point me to examples of utilities published in JOSS?

**Comment by raamana** [comment]
Thanks for pointing me to nilearn's connectome measure. Hiwenet will fit in there very well.

Just like the LedoitWolf covariance is imported from sklearn (which they're not re-coding into nilearn or MNE)
https://github.com/nilearn/nilearn/blob/master/nilearn/connectome/connectivity_matrices.py#L8
https://github.com/mne-tools/mne-python/blob/maint/0.14/mne/cov.py#L871

hiwenet could also be integrated very easily, with the sklearn's fit/transform interface.

Yes it is an utility, and I believe its non-trivial, given its obvious research application and scope of utility, which is not minor.

Now that we discuss integration into other softwares, I need to consider implementing the fit/transform interface.

**Comment by oesteban** [comment]
> I need to consider implementing the fit/transform interface.
This would be a great addition.

> Yes it is an utility, and I believe its non-trivial, given its obvious research application and broad scope of utility, which is not minor.

This touches upon the central question discussed. However, I feel that the minor/major adjective should be analyzed in the space of software engineering and the context of existing software. Scientifically, I have no doubt this is a major contribution necessary to build your preprint and future papers, but IMHO you want to justify how this utility is also a major addition to the neuroimaging-in-python ecosystem.

The following questions are still open:

  - [ ] Get an idea of how well I described this software above (about the two components of hiwenet). I could be missing something - With the addition of #7 I am not sure now that the second component I mentioned up in https://github.com/raamana/hiwenet/issues/8#issuecomment-327639942 does even exist in hiwinet.
  - [ ] https://github.com/raamana/hiwenet/issues/8#issuecomment-327641795 - The answer to this question will be highly valuable to @cMadan and the JOSS editors. If you find some "minor utilities" already published in JOSS, all this discussion would be irrelevant and your submission accepted without doubts. Then, JOSS editors should work on better define that requirement with an exact definition of what is major and minor, and the coordinates in which that should be evaluated.

**Comment by raamana** [comment]
Oscar and Chris, I could certainly give you examples of JOSS accepted software, which I would consider minor utilities (download scripts, calculator of few scores, or applicators of few simple steps, visualization scripts etc), if I were to apply your reasoning (which if I understand correctly is only few functions, doing only one thing, not sufficiently distinguished from existing tools etc).

I am choosing to not name them (and leave it upto you and JOSS editors to develop your own opinion: http://joss.theoj.org/papers/popular?page=14), out of a simple reason, that it would be disrespectful to call them minor utilities even if they serve a handful of people well (regardless of the size of the task). This is a personal opinion and its okay if we disagree - but I personally recognize that most of these are open source, have been made in the spirit of open science and they have already volunteered their time and skills to develop, maintain and share them. I believe you also share many of these ideas.

If I were a JOSS reviewer myself, I wouldn't support duplication of functionality, misappropriation of credit, code stealing and the other trivial things etc.  I would judge the utility of a submission by the quality of product delivered (in the mind of the end-user -- not the reviewer)
 - will it improve the end-user's productivity (again, not the reviewers)? Even if its a small section of people, if it is helpful beyond the trivial, it is worth being considered.
 - is it helpful to have a common utility that is well done, tested and reliable, than each user implementing their own (even if it only takes a week to implement it)?
 
Thanks to your expert review and generous volunteering of time, its been quite improved, and I will continue to improve this as I am able to (given I use it for my research projects). That said, this is still a side project for me, and I will focus on using it for now and let the users drive the development. I may have to reconsider whether to put time towards its publication (not as enthusiastic anymore) or its development as I see it will be helpful to myself and others.

**Comment by raamana** [comment]
You were incredibly helpful in all the ways -- your expert review and most importantly your time and consideration will be appreciated by me. In fact, I've just added acknowledgements towards that now..
https://github.com/raamana/hiwenet/blob/master/docs/about.rst#acknowledgements

which should be updated on its website shortly.

**Comment by cMadan** [comment]
Thank you for the insightful discussion re: JOSS' inclusion criteria. As editors we have also had discussions regarding the scope of the journal and if specific submissions are sufficiently substantial in function (e.g., minor utility, research application). I will direct the JOSS editors to this thread to further our discussions in how we can make the journal criteria clearer.

I think the current submission is sufficiently substantive, but this discussion does nonetheless signal that the function of the submission should be made clearer. In this respect, the statement of need (in the `paper.md`) should be more explicit and demonstrative. It currently gives a broad direction of function, but the addition of a specific statement (only 1 paragraph or so) and related demo dataset would make the submission unarguably sufficient for JOSS. Along these lines, some text about the existing tools that the submission would complement (as discussed, nilearn and mne-tools) would make the submission more approachable to potential users. 

I would also strongly suggest that there be additional references in the paper, to provide better context of the submission. I'm sure there are another 2-3 references beyond the listed preprint that can help convey to a reader what the toolbox does. As it is there is only one paragraph that somewhat conveys the functionality, which I myself find a bit opaque. The paper is intended to not be overly burden-some to the developer, but it also needs to describe the submission's function to a slightly broader audience than those who may use it. (I also think that words should be written out fully, "esp.".)

**Comment by raamana** [comment]
Thanks Chris and Oscar for the clarification. 

I didn't mean the paper.md to be static (as it was at the submission time) - it was prepared to give an idea of what I had mind (with the intention to improve it and not leave it as is), for examples with your comments here. Anyways, I've added another para now (what does hiwenet do?), with references to the API/CLI docs, with concrete examples (and relevant files for a demo dataset). 

Just to push back on the lack of clarity a bit :), the very second sentence in the first paragraph of paper.md says "**This package extracts single-subject (individualized, or intrinsic) networks from node-wise data by computing the edge weights based on histogram distance between the distributions of values within each node**" -- I am not sure if that can be made any more specific, without code/data, both of which are visible in the repo and examples folder. But, I understand we should try do our best to clarify the purpose and functionality in as many ways as possible, including having to repeat it multiple times at multiple places.

I've mentioned the other tools also and how hiwenet relates to them. As I am planning to add a scikit-learn compatible API, I will include more specific examples directly related to nilearn and MNE - but this will happen once I finalize few more things -- as I would like to survey the landscape even more on what interfaces would be great and what tools to target etc.

docs are here: http://hiwenet.readthedocs.io/en/latest/ - I will try to make that the go-to place for documentation (probably even removing README.md in repo to avoid overlap with paper.md, if needed).

Perhaps it was not clear, but paper.bib had already contained more than my preprint. I've added few more. I am sure you agree with me the function of paper.bib is not meant to be lit survey (Author guidelines need to expanded substantially on what is expected). 

I am glad this review is helping to improve the process of JOSS review. Thanks for your time to improve hiwenet. Much appreciate it.

**Comment by oesteban** [comment]
> This package extracts single-subject (individualized, or intrinsic) networks from node-wise data by computing the edge weights based on histogram distance between the distributions of values within each node

Very accurate 👍 

I just wanted to remind my request of a smoke test in travis. The idea shouldn't take more than 20 minutes to implement, and I'm sure Pradeep has a features file ready to use for that test.

Thanks Pradeep for the effort and for a great contribution.

**Comment by cMadan** [comment]
> I didn't mean the paper.md to be static (as it was at the submission time) - it was prepared to give an idea of what I had mind (with the intention to improve it and not leave it as is), for examples with your comments here. Anyways, I've added another para now (what does hiwenet do?), with references to the API/CLI docs, with concrete examples (and relevant files for a demo dataset).

I'm not sure I follow... I feel like the project at the time of submission is intended to be 'ready to be accepted' from the submitter's perspective. So, the `paper.md` should have been complete at that time, not that the reviewer and editor point out how it was incomplete and the author says 'it wasn't supposed to be reviewed yet, it was just a placeholder'. Regardless, the new "What does the hiwenet package do?" section does much to address my prior concerns.

> Perhaps it was not clear, but paper.bib had already contained more than my preprint. I've added few more. I am sure you agree with me the function of paper.bib is not meant to be lit survey (Author guidelines need to expanded substantially on what is expected).

The paper.bib is meant to be the references to go along with the paper.md. It should only have references cited in the paper.md. Reciprocally, all entries in paper.bib should be cited in paper.md--I will let you determine how you wish to make these two files align. This is definitely not intended to be a lit review, but also no one will look at the paper.bib file directly, it's only necessary for paper.md to be compiled into the resulting pdf, and as it is, paper.md only has a single reference--your preprint.

**Comment by raamana** [comment]
Hey guys, sorry for the delay. I had been busy with other projects/deadlines.

Chris, I like your suggestions and have now added the references listed in paper.bib to paper.md. Let me know if I can improve it further.

**Comment by raamana** [comment]
Oscar, I believe I have addressed your comments as noted in https://github.com/openjournals/joss-reviews/issues/380#issuecomment-327850313 via revisions to the paper.md and README and other commits. 

I've also added more analysis and [tests](https://github.com/raamana/hiwenet/blob/master/hiwenet/analyze_distance_behaviour.py) to analyze the behaviour of these distance metrics with changing distance/similarity. These are no mathematical proofs, but I am more confident than earlier that the package is doing what it is supposed to do. I am going to work on this further, as part of my research (and will be updating the package naturally) as I learn more about these distances. This would also partly address #10 as asserting the validity of current implementation is as or more important than checking whether it matches with my earlier matlab implementation. 

Since we last chatted 6 weeks ago, I've improved the package in many ways, including implementing versioneer and option to control the range of histogram edges.

Updated docs, which are generated automatically, are at: http://hiwenet.readthedocs.io/

Take a look and let me know if these changes improve hiwenet and bring it closer to acceptance. Thank you again both for your time and comments to improve hiwenet.

**Comment by raamana** [comment]
just to clarify, the [analysis](https://github.com/raamana/hiwenet/blob/master/hiwenet/analyze_distance_behaviour.py) I mentioned above, is in addition to the tests I wrote for the histogram distances specifically (ensuring their mathematical properties as metrics, whenever they are claimed to be). They've been found helpful and [merged](https://github.com/loli/medpy/pull/40) into the medpy package, and are also independently [run within `hiwenet`](https://github.com/raamana/hiwenet/blob/master/hiwenet/test_medpy.py) package itself for double checking.

**Comment by raamana** [comment]
FYI, new feature added: https://github.com/raamana/hiwenet/issues/5 via ff84e1fbd11c605a8caeb2d0f80f3eaad6bfdc1d

**Comment by raamana** [comment]
Additional non-histogram metrics are implemented via #12.

**Comment by raamana** [comment]
Also, ability to build directed networks (asymmetric adjacency matrices) is added!

Via 7cf61bb

**Comment by raamana** [comment]
Hey Oscar, Chris, I know you guys are extremely busy, if you could take a quick look and let me know if you are happy with the revisions and latest state, or identify what else you would like, that would be great. I am hoping to tick development of this repo off my list soon.

Thanks for your time and expertise in reviewing and improving this repo so far. It's much improved since its submission.

**Comment by oesteban** [comment]
Hi, I assumed that once the review is done, it was just a matter of fixing all the issues for the submitter. I could be wrong.

Anyways, I totally trust your criteria to close the review issues, but if you want me to double check or help I'm happy to come back to this.

**Comment by raamana** [comment]
Thanks Oscar. I believe only the reviewer or editor is supposed to tick them off, once they believe the revisions are done and adequate. Here is the link : https://github.com/openjournals/joss-reviews/issues/380

**Comment by oesteban** [comment]
Cool, I'll finish up today :)

**Comment by raamana** [comment]
Thanks Oscar!

**Comment by oesteban** [comment]
I think this one can be closed now.
